export enum TeamType {
  DEVELOPMENT = 'DEVELOPMENT',
  HR = 'HR',
  MANAGEMENT = 'MANAGEMENT',
  TRADE = 'TRADE',
  SALES = 'SALES',
  SERVICE = 'SERVICE',
  PRODUCTION = 'PRODUCTION',
  EDUCATION = 'EDUCATION',
  MARKETING = 'MARKETING',
  OTHERS = 'OTHERS',
}
